#!/usr/bin/env bash
# gives you information about the alxschool file using the if/else statement

file="alxschool"
if [ -e "$file" ]
then
    echo "$file file exists"
    if [ -s "$file" ]
	then
		echo "alxschool file is not empty"
    else
		echo "alxschool file is empty"
    fi
    if [ -f "$file" ]
	then
		echo "alxschool is a regular file"
    fi
else
    echo "alxschool file does not exist"
fi
